### PR TITLE
limits of setoid families

### PR DESCRIPTION
**Pull request by jonsterling**
If this isn't how you wanted to do it, feel free to close this; also, feel free to suggest identifier name changes, since I haven't fully learnt the conventions employed in this lib.

### CODE REVIEW

**Comment by jonsterling** [comment]
By the way, I wasn't sure how to define the actual setoid for Pi.

**Comment by freebroccolo** [comment]
I haven't had a chance to look through this yet but it should be possible to follow some of the stuff from [here](https://github.com/freebroccolo/agda-kan-semisimplicial-setoids/blob/5717d8c0d4726bf740645ed59887e7c038c35798/src/Main.agda#L156-L196). I didn't quite finish the definition there either but I was following Coquand's notes on the setoid model IIRC.

**Comment by freebroccolo** [comment]
Basically what I think we will need to do is implement the rest of the machinery like for the setoid model, so we need context extension, etc. Then we will want to implement the combinators `lam` and `ap`. Essentially we will be implementing a relative version of the same CCC stuff we have in the base layer.

**Comment by freebroccolo** [comment]
I'll start working on porting some of the stuff from that other repo I linked.

**Comment by jonsterling** [comment]
Great, thanks! I'll close this PR since it looks like you've got it covered :smile:

**Pull request closed without merging**
